# Set the base path for the API
server:
  port: 12001
  servlet:
    context-path: /api/weather

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 12005

security:
  excluded-paths: /actuator/health,/actuator/info,/swagger-ui.html,/swagger-ui/**,/*/api-docs

authentication:
  cors:
    allowed-origin-patterns: http://localhost:12006,https://demo.markpost.dev

logging:
  level:
    root: DEBUG
    nl.markpost.demo: DEBUG

jwt:
  public-key-url: http://authentication-service:12002/api/auth/v1/public-key

---
# Local environment profile
spring:
  config:
    activate:
      on-profile: local
weather:
  cors:
    allowed-origin-patterns: "http://localhost:3000"

---
# UT environment profile
spring:
  config:
    activate:
      on-profile: ut

jwt:
  public-key-url: http://localhost:12002/v1/public-key

security:
  excluded-paths: /actuator/health,/actuator/info,/swagger-ui.html,/swagger-ui/**,/*/api-docs,/v1/forecast
